// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApi.Data;

#nullable disable

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20231023210854_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("SchoolLibrary.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "531a38ed-afbd-4b85-b013-3d9651b66dad",
                            FirstName = "Tom",
                            LastName = "Day",
                            School = "Physics"
                        },
                        new
                        {
                            StudentId = "3e07fe9f-17df-4d99-980d-e77415ad7ec9",
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Geology"
                        },
                        new
                        {
                            StudentId = "9b056d61-f1ee-4b3f-9bce-303a0e2f3a86",
                            FirstName = "Art",
                            LastName = "Ash",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "b8aac510-1fe8-4e3d-979f-943eccba7aea",
                            FirstName = "Mia",
                            LastName = "Hay",
                            School = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
